---
- name: Verify
  hosts: all
  collections:
    - community.general
  tasks:
    - name: Get all ports on hosts
      listen_ports_facts:
    - name: Assert Ingest is listening
      assert:
        that:
          - "8066 in (ansible_facts.tcp_listen | map(attribute='port') | list)"
    - name: Stat files
      stat:
        path: "{{ item }}"
      register: file_stat_results
      loop:
        - /opt/default/ingest_frontend.ini
        - /opt/default/ingest_backend.ini
        - /opt/default/ingest_frontend-cp.ini
        - /opt/default/ingest_frontend
        - /opt/default/ingest_backend
        - /etc/systemd/system/ingest_frontend.service
        - /etc/systemd/system/ingest_backend.service
    - name: Verify files
      assert:
        that:
          - item.exists
      loop: "{{ file_stat_results.results | map(attribute='stat') | list }}"
    - name: Status the service
      systemd:
        name: ingest_frontend
        state: started
    - name: Status the service
      systemd:
        name: ingest_backend
        state: started
    - name: Check Ingest URL
      uri:
        url: http://127.0.0.1:8066/
        return_content: yes
      register: ingest_result
    - name: Assert some content
      assert:
        that:
          - ingest_result.status == 200
