---
- name: "Pacifica: Started uWSGI Service"
  retries: 5
  delay: 5
  register: result
  until: result.get('status', {}).get('SubState', '') == 'running'
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ pacifica_enabled_services }}"
  become: true
