---
- name: apt get update if debian
  apt:
    update_cache: true
  when: "ansible_os_family == 'Debian'"
- name: Install common packages
  package:
    name:
      - curl
      - net-tools
    state: present
- name: Install Debian packages
  package:
    name:
      - gpg-agent
  when: "ansible_os_family == 'Debian'"
- name: Install Redhat packages
  package:
    name:
      - gcc
      - glibc-devel
      - make
      - glibc-langpack-en
  when: "ansible_os_family == 'RedHat'"
- name: Set PostgreSQL for RedHat 8
  set_fact:
    postgresql_packages:
      - postgresql
      - postgresql-devel
      - postgresql-server
      - postgresql-contrib
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version | int >= 8
