---
dependency:
  name: galaxy
  options:
    role-file: molecule/common/requirements.yml
driver:
  name: docker
lint: yamllint . && ansible-lint
platforms:
  - name: in-ubuntu18.04
    image: ubuntu:18.04
    dockerfile: ../ubuntu/Dockerfile.j2
    privileged: true
    capabilities:
      - SYS_ADMIN
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: /lib/systemd/systemd
provisioner:
  name: ansible
verifier:
  name: testinfra
  directory: ../common/in_tests
  additional_files_or_dirs:
    - ../common_tests/test_default.py
    - ../common_tests/test_redis.py
  lint:
    name: pre-commit
