---
- name: Converge
  hosts: all
  pre_tasks:
    - name: install curl
      package:
        name: curl
        state: present
  roles:
    - role: redis
      redis_travis_ci: true
    - role: postgresql
      postgresql_ext_install_dev_headers: true
      postgresql_version: 9.6
      postgresql_databases:
        - name: pacifica_notify
          owner: pacifica
      postgresql_users:
        - name: pacifica
          pass: pacifica
          encrypted: false
    - role: ansible-pacifica
      pacifica_notify_config: &pacifica_notify_config
        celery:
          broker_url: redis://127.0.0.1:6379/0
        database:
          peewee_url: postgres://pacifica:pacifica@127.0.0.1:5432/pacifica_notify
      pacifica_available_services:
        notify_backend:
          ini_config: *pacifica_notify_config
        notify_frontend:
          ini_config: *pacifica_notify_config
      pacifica_enabled_services:
        - notify_frontend
        - notify_backend
