---
dependency:
  name: galaxy
driver:
  name: docker
lint: yamllint . && ansible-lint
platforms:
  - name: centos
    image: centos:7
    privileged: true
    capabilities:
      - SYS_ADMIN
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: /usr/lib/systemd/systemd
  - name: ubuntu
    image: ubuntu:18.04
    dockerfile: ../ubuntu/Dockerfile.j2
    privileged: true
    capabilities:
      - SYS_ADMIN
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: /lib/systemd/systemd
provisioner:
  name: ansible
verifier:
  name: testinfra
  lint:
    name: pre-commit
