---
- name: Converge
  hosts: all
  pre_tasks:
    - name: install curl
      package:
        name: curl
        state: present
    - name: Install development
      package:
        name:
          - gcc
          - glibc-devel
          - make
      when: "ansible_os_family == 'RedHat'"
  roles:
    - role: postgresql
      postgresql_ext_install_dev_headers: true
      postgresql_apt_dependencies: ["python3-psycopg2", "locales"]
      postgresql_version: 10
      postgresql_databases:
        - name: pacifica_metadata
          owner: pacifica
        - name: pacifica_uniqueid
          owner: pacifica
      postgresql_users:
        - name: pacifica
          pass: metadata
    - role: pacifica.ansible_pacifica
      environment:
        PATH: /usr/pgsql-10/bin:{{ ansible_env.PATH }}
      pacifica_enabled_services:
        - metadata
        - policy
        - uniqueid
