---
- name: Converge
  hosts: all
  vars:
    postgresql_ext_install_dev_headers: true
    postgresql_apt_dependencies: ["python3-psycopg2", "locales"]
    postgresql_version: 10
    postgresql_databases:
      - name: pacifica_metadata
        owner: pacifica
      - name: pacifica_uniqueid
        owner: pacifica
    postgresql_users:
      - name: pacifica
        pass: metadata
        password: metadata
  pre_tasks:
    - name: install curl
      package:
        name: curl
        state: present
    - name: Install development
      package:
        name:
          - gcc
          - glibc-devel
          - make
      when: "ansible_os_family == 'RedHat'"
    - name: Set PostgreSQL for RedHat 8
      set_fact:
        postgresql_packages:
          - postgresql
          - postgresql-devel
          - postgresql-server
          - postgresql-contrib
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version | int >= 8
  roles:
    - role: rh7.postgresql
      when: |
        (
          ansible_os_family == 'RedHat' and
          ansible_distribution_major_version | int < 8
        ) or
        ansible_os_family == 'Debian'
    - role: rh8.postgresql
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version | int >= 8
    - role: pacifica.ansible_pacifica
      environment:
        PATH: /usr/pgsql-10/bin:{{ ansible_env.PATH }}
      pacifica_enabled_services:
        - metadata
        - policy
        - uniqueid
