---
- name: Converge
  hosts: all
  pre_tasks:
    - name: install curl
      package:
        name: curl
        state: present
  roles:
    - role: postgresql
      postgresql_ext_install_dev_headers: true
      postgresql_version: 9.6
      postgresql_databases:
        - name: pacifica_metadata
          owner: pacifica
        - name: pacifica_uniqueid
          owner: pacifica
      postgresql_users:
        - name: pacifica
          pass: metadata
          encrypted: false
    - role: ansible-pacifica
      environment:
        PATH: /usr/pgsql-9.6/bin:{{ ansible_env.PATH }}
      pacifica_enabled_services:
        - metadata
        - policy
        - uniqueid
